name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  validate:
    uses: curium-rocks/flows/.github/workflows/golang.yml@main
  image:
    needs:
      - validate
    uses: curium-rocks/flows/.github/workflows/oci-build-image.yml@main
    with:
      image_name: go-background-svc
      registry: ghcr.io/bryopsida
